service:
- docker

language: java
jdk: oraclejdk8

addons:
  apt:
    update: true
    packages:
    - curl
    - docker-ce
    - python-pip
    - git
    - bash

install: true
before_script:
- sudo pip install docker-compose >/dev/null 2>&1
- source <(curl -s https://raw.githubusercontent.com/daggerok/bash-functions/master/main.bash)

script:
- bash ./mvnw
- bash ./gradlew >/dev/null
- bash ./gradlew asciidoctor # docs
- export root=$(pwd)
#
- cd ${root}/first-akka-blood
- bash gradlew >/dev/null 2>&1
- bash build/install/first-akka-blood/bin/first-akka-blood &
- sleep 10
- sudo killall -9 java
- docker-compose build --force-rm
- docker-compose up &
- sleep 10
- docker-compose down -v
- bash gradlew clean distZip >/dev/null
- unzip -o build/distributions/first-akka-blood-0.0.1.zip -d /tmp
- bash /tmp/first-akka-blood-0.0.1/bin/first-akka-blood &
- sleep 10
- sudo killall -9 java
- bash gradlew composeUp
- docker logs -f firstakkablood_first-akka-blood-app_1 &
- sleep 10
- bash gradlew composeDown >/dev/null
#
- >
  for project in \
    scala-gradle-scalatra-spring-boot \
    scala-gradle-testing \
    scala-gradle-spring-boot \
    learn-jvm \
  ; do
    cd "${root}"
    echo "cloning..."
    git clone "https://github.com/daggerok/${project}"
    cd "${project}"
    echo "building..."
    bash gradlew >/dev/null
    echo "${project} done."
  done;

cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle
  - $HOME/.docker

env:
  global:
  - TERM=dumb
  - secure: Of3ahCTqkQ5s+2dwAGUaSJSV4ty4KKoLmzFwZNbwzE6dyOvsBWGa2OG6fIamHhE99Rf2ZulsVW99rfLWOIoaN0Pc105UeWo+SU1VMhk140rNMsVAvVdrDX9W4BhHt6KS0SZ1l7hn+bnorP/ZZCaoP1Shiof6csZ1eN8N0ZQjbx2BAU96zsyFBWoJlQTB4cYF9ce8SWrkvD5Rx0ItbBNNZJwHX35fZ4GM+m4qySwqIfr+2eoIDfv6blC+oQCaFxra9xHx/3IzTsLzB+S0YQfYREP8E1jiNNTRFCXweN+YoDACRQcU+8XvYmR8T1nKFxk+fGl61+y5J3oQYnP0YJPR59kmKV3W2NUn6mZC/jjh7HfXbLeef3xUJIB/OV9JyyGC+NKUHwBciU7rN+Z0qc+PSvh79k/OmLq6iUkOcuf8N9hO13d64eBtYkFkcrTR6PANk01moyMqdfp3vwGSloTJAqPQpNT+smgdSPAhhGwz3H58OVeqJ2MwvnqjfLBGiYRPELQxQUlK4LPiC2FUDAtPoHCHIijbwyCWc1FFQcbzt1xttB+RD1zdqhCgc55xCY19gEogpPtPt895AQtGmDOry9qOWAoCOFm9JNL6SCZN04XDmbzvop0sJCKTSDx1KjonFzdUYhV9GPBUlrXZ/Z4U4D507S4pFYcLOJDeVzwgo5c=

before_deploy:
- cd "${root}"
- ./gradlew documentation

deploy:
  provider: pages
  skip-cleanup: true
  # travis encrypt GITHUB_TOKEN=<your github repo token> --add
  github-token: "$GITHUB_TOKEN"
  keep-history: true
  on:
    branch: master
  local-dir: target/generated-docs
  target_branch: gh-pages
