service:
- docker
sudo: required
group: travis_lts
env:
  global:
    TERM=dumb
language: java
jdk:
- oraclejdk8
- openjdk8
install: true
before_script:
- sudo apt udate -y || true
- sudo apt install -y --no-install-recommends curl docker-ce python-pip git
- sudo pip install docker-compose
- source <(curl -s https://raw.githubusercontent.com/daggerok/bash-functions/master/main.bash)
script:
- bash ./mvnw
- bash ./gradlew
- bash ./gradlew asciidoctor # docs
- export root=$(pwd)
#
- cd ${root}/first-akka-blood
- bash gradlew >/dev/null 2>&1
- bash build/install/first-akka-blood/bin/first-akka-blood &
- sleep 10
- sudo killall -9 java
- docker-compose build --force-rm
- docker-compose up &
- sleep 10
- docker-compose down -v
- bash gradlew clean distZip
- unzip -o build/distributions/first-akka-blood-0.0.1.zip -d /tmp
- bash /tmp/first-akka-blood-0.0.1/bin/first-akka-blood &
- sleep 10
- sudo killall -9 java
- bash gradlew composeUp
- docker logs -f firstakkablood_first-akka-blood-app_1 &
- sleep 10
- bash gradlew composeDown
#
- >
  for project in \
    scala-gradle-scalatra-spring-boot \
    scala-gradle-testing \
    scala-gradle-spring-boot \
    learn-jvm \
  ; do
    cd "${root}"
    echo "cloning..."
    git clone "https://github.com/daggerok/${project}"
    cd "${project}"
    echo "building..."
    bash gradlew
    echo "${project} done."
  done;
cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle
