version: "2.1"

services:

  first-akka-blood-app:
    build:
      context: .
      dockerfile: ./gradle/Dockerfile
    volumes: ["app-data:/home/appuser"]
    networks: [backing-services]

volumes:
  app-data: {}

networks:
  backing-services:
    driver: bridge
